# cloudbuild.yaml
steps:
  # 1 Dockerイメージをビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/correspondence-app/correspondence:v1",
        ".",
      ]

  # 2 Artifact Registry にプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/correspondence-app/correspondence:v1",
      ]

  # 3 Cloud Run にデプロイ（Secret Manager の値を渡す）
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy correspondence-app \
          --image asia-northeast1-docker.pkg.dev/$PROJECT_ID/correspondence-app/correspondence:v1 \
          --region asia-northeast1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY} \
          --set-env-vars NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN} \
          --set-env-vars NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID} \
          --set-env-vars NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET} \
          --set-env-vars NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID} \
          --set-env-vars NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID} \
          --set-env-vars GOOGLE_SPREADSHEET_ID=${_GOOGLE_SPREADSHEET_ID} \
          --set-env-vars GOOGLE_PROJECT_ID=${_GOOGLE_PROJECT_ID} \
          --set-env-vars GOOGLE_CLIENT_EMAIL=${_GOOGLE_CLIENT_EMAIL} \
          --set-secrets GOOGLE_PRIVATE_KEY=GOOGLE_PRIVATE_KEY:latest

images:
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/correspondence-app/correspondence:v1"

timeout: 900s
