export type School = {
  name: string;
  course: string;
  content: string;
  school: string;
  style: string;
  schooling: string;
  attendance: string;
  subAttendance: string;
  target: string;
  firstTuition: number | null;
  secondTuition: number | null;
  thirdTuition: number | null;
  enrollmentFee: number | null;
  april: string;
  may: string;
  june: string;
  july: string;
  august: string;
  september: string;
  october: string;
  november: string;
  december: string;
  january: string;
  february: string;
  march: string;
  anotherTuitionName: string;
  anotherTuition: string;
  picture: string;
  url: string;
  schoolId: string;
  entranceTuition: number | null;
  transferTuition: number | null;
};