export{ default as Header } from "./Header"
export{ default as Form } from "./Form"
export{ default as Login } from "./Login"
export{ default as SearchBar } from "./SearchBar"
// export{ default as SchoolCard } from "./SchoolCard"